baseURL = "http://example.org/"
languageCode = "en-us"
title = "Record Collection"
theme = "mediumish"
summaryLength = 25
copyright = "Jose Maria Nunez-Izu - All rights reserved"
disqusShortname = "shortDisquis"
googleAnalytics = "UA-1XXXXXXX1-X"

[params]
  #logo = "/images/logo.png"
  #description ="the clean blog!"
  #mailchimp = "you can provide a mailchimp-link here"
  # customCSS = ["/styles/styles.css"]

[params.author]
  name = "J"
  thumbnail = "/images/author.jpg"
  description = "Editor"

[params.index]
  picture = "/images/author.jpg"
  title = "J"
  subtitle = "I'm a unique placeholder. Working here and there!"
  mdtext = '''
Currently trying to get this blog running, still don't know what the blog will be about!\
**This textblock is a demonstration of the mdtext-param.**\
### This is a markdown heading
'''
  alertbar = false

[params.social]
  github = "<username>"
  linkedin = "<username>"
  xing = "<username>"
  medium = "<username>"
  twitter = "<username>"

## Main Menu
[[menu.main]]
    name = "Collection"
    weight = 100
    identifier = "collection"
    url = "/collection"
[[menu.main]]
    name = "About Me"
    identifier = "about"
    weight = 200
    url = "/"
